from lithub.models import Group, Label

LABELS_LOCATION = {
    'Location_Group (Lancet 2026)': Group(
        collection='GEO',
        key='Location_Group (Lancet 2026)',
        name='Location grouped by Group (Lancet 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Group (Lancet 2026)|0',
                value=0,
                name='SIDS',
                desc='Article with at least one Location in SIDS',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
            Label(
                column='Location_Group (Lancet 2026)|1',
                value=1,
                name='Asia',
                desc='Article with at least one Location in Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
            Label(
                column='Location_Group (Lancet 2026)|2',
                value=2,
                name='Africa',
                desc='Article with at least one Location in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
            Label(
                column='Location_Group (Lancet 2026)|3',
                value=3,
                name='Europe',
                desc='Article with at least one Location in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
            Label(
                column='Location_Group (Lancet 2026)|4',
                value=4,
                name='Latin America',
                desc='Article with at least one Location in Latin America',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
            Label(
                column='Location_Group (Lancet 2026)|5',
                value=5,
                name='Oceania',
                desc='Article with at least one Location in Oceania',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
            Label(
                column='Location_Group (Lancet 2026)|6',
                value=6,
                name='Northern America',
                desc='Article with at least one Location in Northern America',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (Lancet 2026)',
            ),
        ],
    ),
    'Location_Group (WHO 2026)': Group(
        collection='GEO',
        key='Location_Group (WHO 2026)',
        name='Location grouped by Group (WHO 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Group (WHO 2026)|0',
                value=0,
                name='Europe',
                desc='Article with at least one Location in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (WHO 2026)',
            ),
            Label(
                column='Location_Group (WHO 2026)|1',
                value=1,
                name='Americas',
                desc='Article with at least one Location in Americas',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (WHO 2026)',
            ),
            Label(
                column='Location_Group (WHO 2026)|2',
                value=2,
                name='Africa',
                desc='Article with at least one Location in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (WHO 2026)',
            ),
            Label(
                column='Location_Group (WHO 2026)|3',
                value=3,
                name='Western Pacific',
                desc='Article with at least one Location in Western Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (WHO 2026)',
            ),
            Label(
                column='Location_Group (WHO 2026)|4',
                value=4,
                name='Eastern Mediterranean',
                desc='Article with at least one Location in Eastern Mediterranean',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (WHO 2026)',
            ),
            Label(
                column='Location_Group (WHO 2026)|5',
                value=5,
                name='South-East Asia',
                desc='Article with at least one Location in South-East Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (WHO 2026)',
            ),
        ],
    ),
    'Location_Group (HDI 2026)': Group(
        collection='GEO',
        key='Location_Group (HDI 2026)',
        name='Location grouped by Group (HDI 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Group (HDI 2026)|0',
                value=0,
                name='Very High',
                desc='Article with at least one Location in Very High',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (HDI 2026)',
            ),
            Label(
                column='Location_Group (HDI 2026)|1',
                value=1,
                name='High',
                desc='Article with at least one Location in High',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (HDI 2026)',
            ),
            Label(
                column='Location_Group (HDI 2026)|2',
                value=2,
                name='Medium',
                desc='Article with at least one Location in Medium',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (HDI 2026)',
            ),
            Label(
                column='Location_Group (HDI 2026)|3',
                value=3,
                name='Low',
                desc='Article with at least one Location in Low',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Group (HDI 2026)',
            ),
        ],
    ),
    'Location_Region (IPCC AR6, 6)': Group(
        collection='GEO',
        key='Location_Region (IPCC AR6, 6)',
        name='Location grouped by Region (IPCC AR6, 6)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Region (IPCC AR6, 6)|0',
                value=0,
                name='Developed Countries',
                desc='Article with at least one Location in Developed Countries',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 6)|1',
                value=1,
                name='Africa',
                desc='Article with at least one Location in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 6)|2',
                value=2,
                name='Latin America and Caribbean',
                desc='Article with at least one Location in Latin America and Caribbean',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 6)|3',
                value=3,
                name='Asia and developing Pacific',
                desc='Article with at least one Location in Asia and developing Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 6)|4',
                value=4,
                name='Middle East',
                desc='Article with at least one Location in Middle East',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 6)|5',
                value=5,
                name='Eastern Europe and Central Asia',
                desc='Article with at least one Location in Eastern Europe and Central Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 6)',
            ),
        ],
    ),
    'Location_Region (IPCC AR6, 10)': Group(
        collection='GEO',
        key='Location_Region (IPCC AR6, 10)',
        name='Location grouped by Region (IPCC AR6, 10)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Region (IPCC AR6, 10)|0',
                value=0,
                name='Africa',
                desc='Article with at least one Location in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|1',
                value=1,
                name='Latin America and Caribbean',
                desc='Article with at least one Location in Latin America and Caribbean',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|2',
                value=2,
                name='Europe',
                desc='Article with at least one Location in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|3',
                value=3,
                name='South-East Asia and Pacific',
                desc='Article with at least one Location in South-East Asia and Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|4',
                value=4,
                name='Middle East',
                desc='Article with at least one Location in Middle East',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|5',
                value=5,
                name='Eastern Europe and Central Asia',
                desc='Article with at least one Location in Eastern Europe and Central Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|6',
                value=6,
                name='Southern Asia',
                desc='Article with at least one Location in Southern Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|7',
                value=7,
                name='Australia, Japan, New Zealand',
                desc='Article with at least one Location in Australia, Japan, New Zealand',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|8',
                value=8,
                name='Eastern Asia',
                desc='Article with at least one Location in Eastern Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Location_Region (IPCC AR6, 10)|9',
                value=9,
                name='North America',
                desc='Article with at least one Location in North America',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (IPCC AR6, 10)',
            ),
        ],
    ),
    'Location_Region (WorldBank 2026)': Group(
        collection='GEO',
        key='Location_Region (WorldBank 2026)',
        name='Location grouped by Region (WorldBank 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Region (WorldBank 2026)|0',
                value=0,
                name='Europe & Central Asia',
                desc='Article with at least one Location in Europe & Central Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
            Label(
                column='Location_Region (WorldBank 2026)|1',
                value=1,
                name='Sub-Saharan Africa',
                desc='Article with at least one Location in Sub-Saharan Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
            Label(
                column='Location_Region (WorldBank 2026)|2',
                value=2,
                name='Latin America & Caribbean',
                desc='Article with at least one Location in Latin America & Caribbean',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
            Label(
                column='Location_Region (WorldBank 2026)|3',
                value=3,
                name='East Asia & Pacific',
                desc='Article with at least one Location in East Asia & Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
            Label(
                column='Location_Region (WorldBank 2026)|4',
                value=4,
                name='Middle East, North Africa, Afghanistan & Pakistan',
                desc='Article with at least one Location in Middle East, North Africa, Afghanistan & Pakistan',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
            Label(
                column='Location_Region (WorldBank 2026)|5',
                value=5,
                name='South Asia',
                desc='Article with at least one Location in South Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
            Label(
                column='Location_Region (WorldBank 2026)|6',
                value=6,
                name='North America',
                desc='Article with at least one Location in North America',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Region (WorldBank 2026)',
            ),
        ],
    ),
    'Location_Income group (WorldBank 2026)': Group(
        collection='GEO',
        key='Location_Income group (WorldBank 2026)',
        name='Location grouped by Income group (WorldBank 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Income group (WorldBank 2026)|0',
                value=0,
                name='High income',
                desc='Article with at least one Location in High income',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Income group (WorldBank 2026)',
            ),
            Label(
                column='Location_Income group (WorldBank 2026)|1',
                value=1,
                name='Upper middle income',
                desc='Article with at least one Location in Upper middle income',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Income group (WorldBank 2026)',
            ),
            Label(
                column='Location_Income group (WorldBank 2026)|2',
                value=2,
                name='Lower middle income',
                desc='Article with at least one Location in Lower middle income',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Income group (WorldBank 2026)',
            ),
            Label(
                column='Location_Income group (WorldBank 2026)|3',
                value=3,
                name='Low income',
                desc='Article with at least one Location in Low income',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Income group (WorldBank 2026)',
            ),
        ],
    ),
    'Location_Lending category (WorldBank 2026)': Group(
        collection='GEO',
        key='Location_Lending category (WorldBank 2026)',
        name='Location grouped by Lending category (WorldBank 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Lending category (WorldBank 2026)|0',
                value=0,
                name='IBRD',
                desc='Article with at least one Location in IBRD',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Lending category (WorldBank 2026)',
            ),
            Label(
                column='Location_Lending category (WorldBank 2026)|1',
                value=1,
                name='IDA',
                desc='Article with at least one Location in IDA',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Lending category (WorldBank 2026)',
            ),
            Label(
                column='Location_Lending category (WorldBank 2026)|2',
                value=2,
                name='Blend',
                desc='Article with at least one Location in Blend',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Lending category (WorldBank 2026)',
            ),
        ],
    ),
    'Location_Continent (Name)': Group(
        collection='GEO',
        key='Location_Continent (Name)',
        name='Location grouped by Continent (Name)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Location_Continent (Name)|0',
                value=0,
                name='Africa',
                desc='Article with at least one Location in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
            Label(
                column='Location_Continent (Name)|1',
                value=1,
                name='Asia',
                desc='Article with at least one Location in Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
            Label(
                column='Location_Continent (Name)|2',
                value=2,
                name='Europe',
                desc='Article with at least one Location in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
            Label(
                column='Location_Continent (Name)|3',
                value=3,
                name='North America',
                desc='Article with at least one Location in North America',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
            Label(
                column='Location_Continent (Name)|4',
                value=4,
                name='Oceania',
                desc='Article with at least one Location in Oceania',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
            Label(
                column='Location_Continent (Name)|5',
                value=5,
                name='South America',
                desc='Article with at least one Location in South America',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
            Label(
                column='Location_Continent (Name)|6',
                value=6,
                name='Antarctica',
                desc='Article with at least one Location in Antarctica',
                colour=(0.57, 0.95, 0.6),
                parent='Location_Continent (Name)',
            ),
        ],
    ),
}
LABELS_AFFILIATION = {
    'Affiliation_Group (Lancet 2026)': Group(
        collection='GEO',
        key='Affiliation_Group (Lancet 2026)',
        name='Affiliation grouped by Group (Lancet 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Group (Lancet 2026)|0',
                value=0,
                name='SIDS',
                desc='Article with at least one Affiliation in SIDS',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
            Label(
                column='Affiliation_Group (Lancet 2026)|1',
                value=1,
                name='Asia',
                desc='Article with at least one Affiliation in Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
            Label(
                column='Affiliation_Group (Lancet 2026)|2',
                value=2,
                name='Africa',
                desc='Article with at least one Affiliation in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
            Label(
                column='Affiliation_Group (Lancet 2026)|3',
                value=3,
                name='Europe',
                desc='Article with at least one Affiliation in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
            Label(
                column='Affiliation_Group (Lancet 2026)|4',
                value=4,
                name='Latin America',
                desc='Article with at least one Affiliation in Latin America',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
            Label(
                column='Affiliation_Group (Lancet 2026)|5',
                value=5,
                name='Oceania',
                desc='Article with at least one Affiliation in Oceania',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
            Label(
                column='Affiliation_Group (Lancet 2026)|6',
                value=6,
                name='Northern America',
                desc='Article with at least one Affiliation in Northern America',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (Lancet 2026)',
            ),
        ],
    ),
    'Affiliation_Group (WHO 2026)': Group(
        collection='GEO',
        key='Affiliation_Group (WHO 2026)',
        name='Affiliation grouped by Group (WHO 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Group (WHO 2026)|0',
                value=0,
                name='Europe',
                desc='Article with at least one Affiliation in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (WHO 2026)',
            ),
            Label(
                column='Affiliation_Group (WHO 2026)|1',
                value=1,
                name='Americas',
                desc='Article with at least one Affiliation in Americas',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (WHO 2026)',
            ),
            Label(
                column='Affiliation_Group (WHO 2026)|2',
                value=2,
                name='Africa',
                desc='Article with at least one Affiliation in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (WHO 2026)',
            ),
            Label(
                column='Affiliation_Group (WHO 2026)|3',
                value=3,
                name='Western Pacific',
                desc='Article with at least one Affiliation in Western Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (WHO 2026)',
            ),
            Label(
                column='Affiliation_Group (WHO 2026)|4',
                value=4,
                name='Eastern Mediterranean',
                desc='Article with at least one Affiliation in Eastern Mediterranean',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (WHO 2026)',
            ),
            Label(
                column='Affiliation_Group (WHO 2026)|5',
                value=5,
                name='South-East Asia',
                desc='Article with at least one Affiliation in South-East Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (WHO 2026)',
            ),
        ],
    ),
    'Affiliation_Group (HDI 2026)': Group(
        collection='GEO',
        key='Affiliation_Group (HDI 2026)',
        name='Affiliation grouped by Group (HDI 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Group (HDI 2026)|0',
                value=0,
                name='Very High',
                desc='Article with at least one Affiliation in Very High',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (HDI 2026)',
            ),
            Label(
                column='Affiliation_Group (HDI 2026)|1',
                value=1,
                name='High',
                desc='Article with at least one Affiliation in High',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (HDI 2026)',
            ),
            Label(
                column='Affiliation_Group (HDI 2026)|2',
                value=2,
                name='Medium',
                desc='Article with at least one Affiliation in Medium',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (HDI 2026)',
            ),
            Label(
                column='Affiliation_Group (HDI 2026)|3',
                value=3,
                name='Low',
                desc='Article with at least one Affiliation in Low',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Group (HDI 2026)',
            ),
        ],
    ),
    'Affiliation_Region (IPCC AR6, 6)': Group(
        collection='GEO',
        key='Affiliation_Region (IPCC AR6, 6)',
        name='Affiliation grouped by Region (IPCC AR6, 6)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Region (IPCC AR6, 6)|0',
                value=0,
                name='Developed Countries',
                desc='Article with at least one Affiliation in Developed Countries',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 6)|1',
                value=1,
                name='Africa',
                desc='Article with at least one Affiliation in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 6)|2',
                value=2,
                name='Latin America and Caribbean',
                desc='Article with at least one Affiliation in Latin America and Caribbean',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 6)|3',
                value=3,
                name='Asia and developing Pacific',
                desc='Article with at least one Affiliation in Asia and developing Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 6)|4',
                value=4,
                name='Middle East',
                desc='Article with at least one Affiliation in Middle East',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 6)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 6)|5',
                value=5,
                name='Eastern Europe and Central Asia',
                desc='Article with at least one Affiliation in Eastern Europe and Central Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 6)',
            ),
        ],
    ),
    'Affiliation_Region (IPCC AR6, 10)': Group(
        collection='GEO',
        key='Affiliation_Region (IPCC AR6, 10)',
        name='Affiliation grouped by Region (IPCC AR6, 10)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|0',
                value=0,
                name='Africa',
                desc='Article with at least one Affiliation in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|1',
                value=1,
                name='Latin America and Caribbean',
                desc='Article with at least one Affiliation in Latin America and Caribbean',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|2',
                value=2,
                name='Europe',
                desc='Article with at least one Affiliation in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|3',
                value=3,
                name='South-East Asia and Pacific',
                desc='Article with at least one Affiliation in South-East Asia and Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|4',
                value=4,
                name='Middle East',
                desc='Article with at least one Affiliation in Middle East',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|5',
                value=5,
                name='Eastern Europe and Central Asia',
                desc='Article with at least one Affiliation in Eastern Europe and Central Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|6',
                value=6,
                name='Southern Asia',
                desc='Article with at least one Affiliation in Southern Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|7',
                value=7,
                name='Australia, Japan, New Zealand',
                desc='Article with at least one Affiliation in Australia, Japan, New Zealand',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|8',
                value=8,
                name='Eastern Asia',
                desc='Article with at least one Affiliation in Eastern Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
            Label(
                column='Affiliation_Region (IPCC AR6, 10)|9',
                value=9,
                name='North America',
                desc='Article with at least one Affiliation in North America',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (IPCC AR6, 10)',
            ),
        ],
    ),
    'Affiliation_Region (WorldBank 2026)': Group(
        collection='GEO',
        key='Affiliation_Region (WorldBank 2026)',
        name='Affiliation grouped by Region (WorldBank 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Region (WorldBank 2026)|0',
                value=0,
                name='Europe & Central Asia',
                desc='Article with at least one Affiliation in Europe & Central Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Region (WorldBank 2026)|1',
                value=1,
                name='Sub-Saharan Africa',
                desc='Article with at least one Affiliation in Sub-Saharan Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Region (WorldBank 2026)|2',
                value=2,
                name='Latin America & Caribbean',
                desc='Article with at least one Affiliation in Latin America & Caribbean',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Region (WorldBank 2026)|3',
                value=3,
                name='East Asia & Pacific',
                desc='Article with at least one Affiliation in East Asia & Pacific',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Region (WorldBank 2026)|4',
                value=4,
                name='Middle East, North Africa, Afghanistan & Pakistan',
                desc='Article with at least one Affiliation in Middle East, North Africa, Afghanistan & Pakistan',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Region (WorldBank 2026)|5',
                value=5,
                name='South Asia',
                desc='Article with at least one Affiliation in South Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Region (WorldBank 2026)|6',
                value=6,
                name='North America',
                desc='Article with at least one Affiliation in North America',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Region (WorldBank 2026)',
            ),
        ],
    ),
    'Affiliation_Income group (WorldBank 2026)': Group(
        collection='GEO',
        key='Affiliation_Income group (WorldBank 2026)',
        name='Affiliation grouped by Income group (WorldBank 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Income group (WorldBank 2026)|0',
                value=0,
                name='High income',
                desc='Article with at least one Affiliation in High income',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Income group (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Income group (WorldBank 2026)|1',
                value=1,
                name='Upper middle income',
                desc='Article with at least one Affiliation in Upper middle income',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Income group (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Income group (WorldBank 2026)|2',
                value=2,
                name='Lower middle income',
                desc='Article with at least one Affiliation in Lower middle income',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Income group (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Income group (WorldBank 2026)|3',
                value=3,
                name='Low income',
                desc='Article with at least one Affiliation in Low income',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Income group (WorldBank 2026)',
            ),
        ],
    ),
    'Affiliation_Lending category (WorldBank 2026)': Group(
        collection='GEO',
        key='Affiliation_Lending category (WorldBank 2026)',
        name='Affiliation grouped by Lending category (WorldBank 2026)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Lending category (WorldBank 2026)|0',
                value=0,
                name='IBRD',
                desc='Article with at least one Affiliation in IBRD',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Lending category (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Lending category (WorldBank 2026)|1',
                value=1,
                name='IDA',
                desc='Article with at least one Affiliation in IDA',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Lending category (WorldBank 2026)',
            ),
            Label(
                column='Affiliation_Lending category (WorldBank 2026)|2',
                value=2,
                name='Blend',
                desc='Article with at least one Affiliation in Blend',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Lending category (WorldBank 2026)',
            ),
        ],
    ),
    'Affiliation_Continent (Name)': Group(
        collection='GEO',
        key='Affiliation_Continent (Name)',
        name='Affiliation grouped by Continent (Name)',
        type='multi',
        colour=(0.57, 0.95, 0.6),
        labels=[
            Label(
                column='Affiliation_Continent (Name)|0',
                value=0,
                name='Africa',
                desc='Article with at least one Affiliation in Africa',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
            Label(
                column='Affiliation_Continent (Name)|1',
                value=1,
                name='Asia',
                desc='Article with at least one Affiliation in Asia',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
            Label(
                column='Affiliation_Continent (Name)|2',
                value=2,
                name='Europe',
                desc='Article with at least one Affiliation in Europe',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
            Label(
                column='Affiliation_Continent (Name)|3',
                value=3,
                name='North America',
                desc='Article with at least one Affiliation in North America',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
            Label(
                column='Affiliation_Continent (Name)|4',
                value=4,
                name='Oceania',
                desc='Article with at least one Affiliation in Oceania',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
            Label(
                column='Affiliation_Continent (Name)|5',
                value=5,
                name='South America',
                desc='Article with at least one Affiliation in South America',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
            Label(
                column='Affiliation_Continent (Name)|6',
                value=6,
                name='Antarctica',
                desc='Article with at least one Affiliation in Antarctica',
                colour=(0.57, 0.95, 0.6),
                parent='Affiliation_Continent (Name)',
            ),
        ],
    ),
}
